############################################
[[main]]
name = 'À propos'
identifier = 'About us'
pageRef = '/about'
weight = 100

[[main]]
name = 'Vision & valeurs'
identifier = 'Vision & Values'
pageRef = '/about/vision-and-values'
parent = 'About us'
weight = 110

[[main]]
name = 'Stratégie 2025-2027'
identifier = 'Strategic Plan 2025-2027'
url = '/efia-plan-strategique-2025-2027.pdf'
parent = 'About us'
weight = 120

[[main]]
name = "Project d'école"
identifier = 'School Project'
url = '/efia-projet-ecole-2025-2028.pdf'
parent = 'About us'
weight = 125

[[main]]
name = 'Organigramme'
identifier = 'Organisational Chart'
url = '/efia_organigramme_2026.pdf'
parent = 'About us'
weight = 127

[[main]]
name = "Conseil d'administration"
identifier = 'Board of Trustees'
pageRef = '/about/board-of-trustees'
parent = 'About us'
weight = 128

[[main]]
name = "L'équipe"
identifier = 'Our team'
pageRef = '/about/team'
parent = 'About us'
weight = 130

[[main]]
name = "Nos installations"
identifier = 'Premises'
pageRef = '/about/premises'
parent = 'About us'
weight = 140

[[main]]
name = "École Enviro"
identifier = 'Enviroschool'
pageRef = '/about/enviroschool'
parent = 'About us'
weight = 145

[[main]]
name = "Inspection ERO 2025"
identifier = 'ERO Inspection 2025'
pageRef = '/about/ero-inspection-2025'
parent = 'About us'
weight = 150

[[main]]
name = 'Témoignages'
identifier = 'Testimonials'
pageRef = '/about/testimonials'
parent = 'About us'
weight = 160

[[main]]
name = "FAQ"
identifier = 'FAQ'
pageRef = '/about/faq'
parent = 'About us'
weight = 170


############################################
[[main]]
name = 'Programme'
identifier = 'Learning'
pageRef = '/learning'
weight = 200

[[main]]
name = 'Le programme français'
identifier = 'The French Curriculum'
pageRef = '/learning/french-curriculum'
parent = 'Learning'
weight = 210

[[main]]
name = 'Les professeurs présentent notre programme'
identifier = 'Teachers Present Our Program'
pageRef = '/learning/teachers-present-our-programme'
parent = 'Learning'
weight = 220

[[main]]
name = 'Les atouts du bilinguisme'
identifier = 'The Advantages of Bilingualism'
pageRef = '/learning/bilingualism'
parent = 'Learning'
weight = 230

[[main]]
name = "Homologation AEFE"
identifier = 'AEFE Accreditation'
pageRef = '/learning/aefe'
parent = 'Learning'
weight = 240


############################################
[[main]]
name = 'Vie des élèves'
identifier = 'School Life'
pageRef = '/school-life'
weight = 300

[[main]]
name = 'Calendrier scolaire et horaires'
identifier = 'Term Dates & School Times'
pageRef = '/school-life/term-dates-and-school-times'
parent = 'School Life'
weight = 310

[[main]]
name = 'Uniforme scolaire'
identifier = 'School Uniform'
pageRef = '/school-life/school-uniform'
parent = 'School Life'
weight = 320

[[main]]
name = 'Fournitures scolaires'
identifier = 'School Supplies'
url = 'https://www.myschool.co.nz/ECOLE'
parent = 'School Life'
weight = 325

[[main]]
name = 'Ordinateur portable (AVEC)'
identifier = 'Bring Your Own Device'
pageRef = '/school-life/byod'
parent = 'School Life'
weight = 327

[[main]]
name = 'Politiques et procédures'
identifier = 'Policies and Procedures'
pageRef = '/school-life/policies-and-procedures'
parent = 'School Life'
weight = 340

[[main]]
name = "Dons"
identifier = 'Donations'
pageRef = '/school-life/donations'
parent = 'School Life'
weight = 350

# [[main]]
# name = "Goodies"
# identifier = 'Goodies'
# pageRef = '/school-life/goodies'
# parent = 'School Life'
# weight = 355

[[main]]
name = "Activités périscolaires"
identifier = 'After-School Activities'
pageRef = '/school-life/after-school'
parent = 'School Life'
weight = 360

[[main]]
name = "Programme de vacances pour enfants"
identifier = 'Children Holiday Programme'
pageRef = '/school-life/children-holiday-programme'
parent = 'School Life'
weight = 370

[[main]]
name = "Adhésion Alliance Française"
identifier = 'Alliance Française Auckland Membership'
pageRef = '/school-life/afa-membership'
parent = 'School Life'
weight = 380

[[main]]
name = "Ressources supplémentaires"
identifier = 'Additional Resources'
pageRef = '/school-life/additional-resources'
parent = 'School Life'
weight = 390

[[main]]
name = "Newsletter"
identifier = 'Newsletter'
url = 'https://drive.google.com/drive/folders/1daNYgJ0yImvKDEhpijC5OKdHMRpQVFrL'
parent = 'School Life'
weight = 395


############################################
[[main]]
name = 'Sport'
identifier = 'Sports'
pageRef = '/sports'
weight = 400

[[main]]
name = 'Remuera Rackets Club'
identifier = 'Remuera Rackets Club'
pageRef = '/sports/remuera-rackets-club'
parent = 'Sports'
weight = 410

[[main]]
name = 'Les Mills – Born to Move'
identifier = 'Les Mills – Born to Move'
pageRef = '/sports/les-mills-born-to-move'
parent = 'Sports'
weight = 420

[[main]]
name = 'Sécurité aquatique et techniques de survie'
identifier = 'Water Safety Awareness & Survival Skills'
pageRef = '/sports/water-safety'
parent = 'Sports'
weight = 430


############################################
[[main]]
name = 'Inscription'
identifier = 'Enrolment'
pageRef = '/enrolment'
weight = 500


############################################
[[main]]
name = 'Étudiants internationaux'
identifier = 'International Students'
pageRef = '/international-students'
weight = 600

############################################
[[main]]
name = 'Recrutement'
identifier = 'Recruitment'
pageRef = '/recruitment'
weight = 700

############################################
[[main]]
name = 'Contact'
identifier = 'Contact us'
pageRef = '/contact'
weight = 800
